name: real_state_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter


  # flutter_lints: ^3.0.0

flutter:

  
  uses-material-design: true

  assets:
    - assets/images/
 
  fonts:
    - family: karla
      fonts:
        - asset: assets/fonts/Karla-Bold.ttf
          weight: 700
        - asset: assets/fonts/Karla-Medium.ttf
          weight: 500
        - asset: assets/fonts/Karla-Regular.ttf
          weight: 400    
  
